sudo: required
language: node_js
node_js:
  - 'node'
  - '6'
  - '5'
  - '4'

before_install:
  - npm install -g node-gyp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
